// DOCX -> HWPX Runner Builder
// Pure client-side: upload DOCX -> bundle with pipeline/*.ps1 -> download zip
// User extracts on Windows and runs run.cmd which executes Word + Hangul COM locally.

const PIPELINE_FILES = [
  "paste_word_to_new_hangul.ps1",
  "stretch_hwpx_layout.ps1",
  "reflow_with_hangul_engine.ps1",
  "compare_rendered_pages.ps1"
];

const RUN_CMD = `@echo off
setlocal
cd /d "%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -File ".\\run.ps1"
pause
`;

const README_TXT = `DOCX -> HWPX Runner
====================

Generated by https://hwp-proposal-cloud.vercel.app

CONTENTS:
  source.docx          your uploaded DOCX
  pipeline\\*.ps1       Word/Hangul conversion scripts
  run.cmd              double-click entry point
  run.ps1              PowerShell orchestrator

REQUIREMENTS (on this Windows PC):
  - Microsoft Word
  - Hancom Hangul 2020 (한컴 한글 2020) -- run it once interactively first to accept license
  - ImageMagick + Ghostscript (only if the compare report step is enabled)
  - PowerShell 5+

HOW TO RUN:
  1. Make sure source.docx is the file you want to convert.
  2. Double-click run.cmd
     -- OR --
     open PowerShell in this folder and run:  .\\run.ps1
  3. Wait until you see "=== DONE".
  4. Open final.hwpx in Hangul.

CUSTOMIZE:
  - The Factor parameter (default 2.02) controls layout stretch.
    Edit run.ps1 line:  $Factor = "2.02"
  - To skip the optional compare step (no ImageMagick / Ghostscript needed),
    delete or comment out the last command in run.ps1.

TROUBLESHOOTING:
  - "Word.Application not found"           -> Repair or reinstall Microsoft Word.
  - "Cannot create HwpCtrl"                -> Open Hancom Hangul once manually first.
  - "Execution Policy" error               -> Run as regular user (not admin) and try
                                              powershell -ExecutionPolicy Bypass -File .\\run.ps1
  - Hangul script security warning         -> Hangul -> 도구 -> 환경설정 -> 보안
                                              -> 스크립트 보안 -> 보통 or 낮음
`;

function buildRunPs1({ factor, compare }) {
  const compareBlock = compare ? `
Write-Host "=== Step 4 (optional): compare rendered pages"
try {
  powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "compare_rendered_pages.ps1") \`
    -SourceDocx $source -CandidateHwpx $OutputFinal -WorkDir (Join-Path $Root "compare")
} catch {
  Write-Host "compare step failed (ImageMagick or Ghostscript missing). Skipping. Error: $($_.Exception.Message)" -ForegroundColor Yellow
}
` : `
# compare step disabled at bundle time
`;

  return `param(
  [string]$SourceDocx  = ".\\source.docx",
  [string]$OutputFinal = ".\\final.hwpx",
  [string]$Factor      = "${factor}"
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
Set-Location $Root

$pipeline = Join-Path $Root "pipeline"
$source   = (Resolve-Path $SourceDocx).Path
$rich     = Join-Path $Root "word_rich_paste.hwpx"
$stretch  = Join-Path $Root "stretched.hwpx"

Write-Host "=== Step 1: Word DOCX -> Hangul HWPX (paste through Word + Hangul COM)"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "paste_word_to_new_hangul.ps1") \`
  -SourceDocx $source -OutputHwpx $rich

Write-Host "=== Step 2: stretch HWPX layout (factor $Factor)"
powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $pipeline "stretch_hwpx_layout.ps1") \`
  -InputHwpx $rich -OutputHwpx $stretch -Factor $Factor

Write-Host "=== Step 3: reflow through Hangul engine"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "reflow_with_hangul_engine.ps1") \`
  -InputHwpx $stretch -OutputHwpx $OutputFinal
${compareBlock}
Write-Host ""
Write-Host "=== DONE: $OutputFinal" -ForegroundColor Green
`;
}

const $ = (id) => document.getElementById(id);

const els = {
  form: $("form"),
  docxInput: $("docxInput"),
  docxName: $("docxName"),
  factor: $("factor"),
  compare: $("compare"),
  run: $("run"),
  statusCard: $("statusCard"),
  status: $("jobStatus"),
  zipSize: $("zipSize"),
  log: $("jobLog"),
  downloads: $("downloads")
};

els.docxInput.addEventListener("change", () => {
  const f = els.docxInput.files?.[0];
  els.docxName.textContent = f ? `${f.name} (${(f.size / 1024).toFixed(1)} KB)` : "선택된 파일 없음";
});

els.form.addEventListener("submit", async (e) => {
  e.preventDefault();
  await build();
});

function log(line) {
  els.log.textContent += line + "\n";
  els.log.scrollTop = els.log.scrollHeight;
}

function setStatus(s) {
  els.status.textContent = s;
}

async function build() {
  const file = els.docxInput.files?.[0];
  if (!file) {
    alert("DOCX 파일을 선택해주세요.");
    return;
  }
  if (!/\.docx$/i.test(file.name)) {
    alert("DOCX 확장자 파일만 지원합니다.");
    return;
  }

  els.statusCard.classList.remove("hidden");
  els.log.textContent = "";
  els.downloads.innerHTML = "";
  els.zipSize.textContent = "-";
  els.run.disabled = true;

  try {
    setStatus("ZIP 만드는 중…");
    log(`▸ 입력 DOCX: ${file.name} (${(file.size / 1024).toFixed(1)} KB)`);

    const factor = (els.factor.value || "2.02").trim();
    const compareOn = els.compare.value === "yes";
    log(`▸ 설정: Factor=${factor}, 비교 리포트=${compareOn ? "켜짐" : "꺼짐"}`);

    const zip = new JSZip();
    zip.file("source.docx", file);
    zip.file("run.cmd", RUN_CMD);
    zip.file("run.ps1", buildRunPs1({ factor, compare: compareOn }));
    zip.file("README.txt", README_TXT);

    const pipelineFolder = zip.folder("pipeline");
    log(`▸ pipeline/*.ps1 ${PIPELINE_FILES.length}개 fetch`);
    for (const name of PIPELINE_FILES) {
      const resp = await fetch(`/pipeline/${name}`);
      if (!resp.ok) throw new Error(`pipeline/${name} 다운로드 실패: ${resp.status}`);
      const text = await resp.text();
      pipelineFolder.file(name, text);
    }

    log("▸ ZIP 압축 중…");
    const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
    const sizeKb = (blob.size / 1024).toFixed(1);
    els.zipSize.textContent = `${sizeKb} KB`;
    log(`▸ ZIP 생성 완료: ${sizeKb} KB`);

    const stamp = new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14);
    const zipName = `hwp-runner-${stamp}.zip`;
    appendDownload(els.downloads, zipName, blob, "변환 번들 ZIP 다운로드");

    setStatus("완료");
    log("▸ ZIP을 PC에서 풀고 run.cmd 더블클릭하세요.");
  } catch (error) {
    setStatus("실패");
    log("✕ " + (error.message || String(error)));
    console.error(error);
  } finally {
    els.run.disabled = false;
  }
}

function appendDownload(container, filename, blob, label) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.textContent = "↓ " + label;
  container.appendChild(a);
}
