// HWP Proposal Cloud — pure client-side
// 1) Read HWPX (zip) and extract <hp:t> text
// 2) Call OpenAI Chat Completions API with user-supplied key
// 3) Bundle local-runner.zip { generated.md, pipeline/*.ps1, run.cmd, run.ps1, README.txt }
// 4) Offer downloads

const PIPELINE_FILES = [
  "paste_word_to_new_hangul.ps1",
  "stretch_hwpx_layout.ps1",
  "reflow_with_hangul_engine.ps1",
  "compare_rendered_pages.ps1",
  "create_docx_from_text.ps1",
  "extract_hwpx_text.ps1"
];

const RUN_CMD = `@echo off
setlocal
cd /d "%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -File ".\\run.ps1" %*
pause
`;

const RUN_PS1 = `param(
  [string]$BriefMarkdown = ".\\generated.md",
  [string]$OutputFinal   = ".\\final.hwpx",
  [string]$Factor        = "2.02"
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
Set-Location $Root

$pipeline = Join-Path $Root "pipeline"
$source   = Join-Path $Root "source.docx"
$rich     = Join-Path $Root "word_rich_paste.hwpx"
$stretch  = Join-Path $Root "stretched.hwpx"

Write-Host "=== Step 1: Markdown -> source.docx (Word COM)"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "create_docx_from_text.ps1") \`
  -InputText $BriefMarkdown -OutputDocx $source

Write-Host "=== Step 2: Word DOCX -> Hangul HWPX"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "paste_word_to_new_hangul.ps1") \`
  -SourceDocx $source -OutputHwpx $rich

Write-Host "=== Step 3: stretch layout"
powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $pipeline "stretch_hwpx_layout.ps1") \`
  -InputHwpx $rich -OutputHwpx $stretch -Factor $Factor

Write-Host "=== Step 4: reflow through Hangul"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "reflow_with_hangul_engine.ps1") \`
  -InputHwpx $stretch -OutputHwpx $OutputFinal

Write-Host "=== DONE: $OutputFinal"
`;

const README_TXT = `HWP Proposal Cloud — Local Runner
==================================

This bundle was generated by the cloud frontend.

CONTENTS:
  generated.md       GPT-generated Markdown draft
  pipeline\\*.ps1     Word/Hangul conversion scripts
  run.cmd            Double-click entry point
  run.ps1            PowerShell orchestrator

REQUIREMENTS (on this Windows PC):
  - Microsoft Word
  - Hancom Hangul 2020 (한컴 한글 2020)
  - ImageMagick (for compare_rendered_pages.ps1, optional)
  - Ghostscript (for compare_rendered_pages.ps1, optional)
  - PowerShell 5+

HOW TO RUN:
  1. Extract this zip somewhere convenient.
  2. (Optional) Edit generated.md to refine the GPT draft.
  3. Double-click run.cmd  -- OR --  open PowerShell and run:
       .\\run.ps1
  4. Wait until you see "=== DONE".
  5. Open final.hwpx in Hangul.

TROUBLESHOOTING:
  - "Word.Application not found": Install or repair Microsoft Word.
  - "Cannot create HwpCtrl": Install Hancom Hangul 2020, run it once interactively to accept the license.
  - "Execution Policy" error: Run PowerShell as user (not admin) and try .\\run.ps1 directly.
`;

const $ = (id) => document.getElementById(id);

const els = {
  form: $("form"),
  apiKey: $("apiKey"),
  template: $("templateInput"),
  templateName: $("templateName"),
  brief: $("briefInput"),
  reference: $("referenceInput"),
  model: $("model"),
  run: $("run"),
  statusCard: $("statusCard"),
  status: $("jobStatus"),
  charCount: $("charCount"),
  log: $("jobLog"),
  downloads: $("downloads")
};

// Persist key locally so the user doesn't have to re-enter
try {
  const cachedKey = localStorage.getItem("openai_api_key") || "";
  if (cachedKey) els.apiKey.value = cachedKey;
} catch (_) {}
els.apiKey.addEventListener("change", () => {
  try { localStorage.setItem("openai_api_key", els.apiKey.value.trim()); } catch (_) {}
});

els.template.addEventListener("change", () => {
  const file = els.template.files?.[0];
  els.templateName.textContent = file ? file.name : "선택된 파일 없음";
});

els.form.addEventListener("submit", async (event) => {
  event.preventDefault();
  await runJob();
});

function log(line) {
  els.log.textContent += line + "\n";
  els.log.scrollTop = els.log.scrollHeight;
}

function setStatus(label) {
  els.status.textContent = label;
}

async function runJob() {
  const apiKey = els.apiKey.value.trim();
  const file = els.template.files?.[0];
  const brief = els.brief.value.trim();
  const reference = els.reference.value.trim();
  const model = els.model.value;

  if (!apiKey || !apiKey.startsWith("sk-")) {
    alert("OpenAI API Key를 입력해주세요 (sk-… 또는 sk-proj-…).");
    return;
  }
  if (!file) {
    alert("HWPX 양식 파일을 선택해주세요.");
    return;
  }
  if (brief.length < 10) {
    alert("작성 지시를 좀 더 구체적으로 입력해주세요 (10자 이상).");
    return;
  }

  els.statusCard.classList.remove("hidden");
  els.log.textContent = "";
  els.downloads.innerHTML = "";
  els.charCount.textContent = "-";
  els.run.disabled = true;

  try {
    setStatus("HWPX 텍스트 추출 중…");
    log(`▸ HWPX 파일 읽기: ${file.name} (${(file.size / 1024).toFixed(1)} KB)`);
    const templateText = await extractHwpxText(file);
    log(`▸ 양식 텍스트 ${templateText.length}자 추출`);

    setStatus("GPT 초안 생성 중…");
    log(`▸ OpenAI ${model} 호출 시작`);
    const draft = await callOpenAI({ apiKey, model, templateText, brief, reference });
    els.charCount.textContent = `${draft.length.toLocaleString()}자`;
    log(`▸ 초안 ${draft.length}자 수신 완료`);

    setStatus("로컬 실행용 ZIP 빌드 중…");
    log("▸ pipeline/*.ps1 + generated.md + run.cmd 묶기");
    const blob = await buildRunnerZip({ draft });
    const stamp = new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14);
    const zipName = `hwp-runner-${stamp}.zip`;

    const mdBlob = new Blob([draft], { type: "text/markdown; charset=utf-8" });
    appendDownload(els.downloads, zipName, blob, "내 PC 실행용 ZIP 다운로드");
    appendDownload(els.downloads, `generated-${stamp}.md`, mdBlob, "Markdown 초안만 받기", true);

    setStatus("완료");
    log("▸ 다운로드 준비 완료 — ZIP을 PC에서 풀고 run.cmd 실행하세요");
  } catch (error) {
    setStatus("실패");
    log("✕ " + (error.message || String(error)));
    console.error(error);
  } finally {
    els.run.disabled = false;
  }
}

async function extractHwpxText(file) {
  const buf = await file.arrayBuffer();
  const zip = await JSZip.loadAsync(buf);
  const xmls = [];
  zip.forEach((path, entry) => {
    if (entry.dir) return;
    if (!/section\d*\.xml$/i.test(path) && !/Contents\/.+\.xml$/i.test(path)) return;
    xmls.push({ path, entry });
  });
  xmls.sort((a, b) => a.path.localeCompare(b.path));

  const chunks = [];
  for (const { entry } of xmls) {
    const xml = await entry.async("string");
    const matches = xml.matchAll(/<hp:t[^>]*>([\s\S]*?)<\/hp:t>/g);
    for (const m of matches) {
      const text = decodeXmlEntities(m[1]).replace(/\s+/g, " ").trim();
      if (text) chunks.push(text);
    }
  }
  return chunks.join("\n");
}

function decodeXmlEntities(s) {
  return s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
    .replace(/&amp;/g, "&");
}

async function callOpenAI({ apiKey, model, templateText, brief, reference }) {
  const systemPrompt = [
    "You draft Korean government / R&D proposal documents.",
    "Use the uploaded Hangul template text as the structural guide.",
    "Return only clean Markdown suitable for conversion into a Word document.",
    "Use #, ##, and ### headings. Do NOT wrap your answer in code fences.",
    "Write in formal Korean business style. Preserve section order when clear."
  ].join(" ");

  const userInput = [
    "## 작성할 문서의 한글 양식에서 추출한 텍스트",
    templateText.slice(0, 18000) || "(양식 텍스트 추출 실패 또는 비어 있음)",
    "",
    "## 사용자 작성 지시",
    brief,
    "",
    "## 추가 참고자료",
    reference || "(없음)"
  ].join("\n");

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userInput }
      ],
      temperature: 0.4,
      max_tokens: 8000
    })
  });

  if (!response.ok) {
    const errText = await response.text().catch(() => "");
    throw new Error(`OpenAI ${response.status}: ${errText.slice(0, 240)}`);
  }
  const payload = await response.json();
  const text = payload.choices?.[0]?.message?.content;
  if (!text || text.trim().length < 20) {
    throw new Error("OpenAI 응답이 너무 짧거나 비어 있습니다.");
  }
  return text.trim();
}

async function buildRunnerZip({ draft }) {
  const zip = new JSZip();
  zip.file("generated.md", draft);
  zip.file("run.cmd", RUN_CMD);
  zip.file("run.ps1", RUN_PS1);
  zip.file("README.txt", README_TXT);
  const pipelineFolder = zip.folder("pipeline");
  for (const name of PIPELINE_FILES) {
    const url = `/pipeline/${name}`;
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`pipeline/${name} 다운로드 실패: ${resp.status}`);
    const text = await resp.text();
    pipelineFolder.file(name, text);
  }
  return await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

function appendDownload(container, filename, blob, label, secondary = false) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.textContent = "↓ " + label;
  if (secondary) a.classList.add("secondary");
  container.appendChild(a);
}
