// DOCX -> HWPX Runner Builder (no AI, no API key)
// Bundles user's DOCX + pipeline/*.ps1 + GUI launcher (convert.vbs) + fallback run.cmd

const PIPELINE_FILES = [
  "paste_word_to_new_hangul.ps1",
  "stretch_hwpx_layout.ps1",
  "reflow_with_hangul_engine.ps1",
  "compare_rendered_pages.ps1"
];

// Primary GUI launcher — double-click to convert, no terminal visible
const CONVERT_VBS = `' DOCX -> HWPX GUI launcher
' Double-click this file. PowerShell runs hidden in the background.
Option Explicit

Dim shell, fso, scriptDir, docxPath, runPs1, finalPath, ans, exitCode
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
docxPath = scriptDir & "\\source.docx"
runPs1   = scriptDir & "\\run.ps1"
finalPath = scriptDir & "\\final.hwpx"

If Not fso.FileExists(docxPath) Then
  MsgBox "source.docx 가 이 폴더에 없습니다." & vbCrLf & vbCrLf & _
         "이 ZIP을 풀어 그대로 둔 채로 실행해 주세요.", _
         vbCritical, "DOCX -> HWPX"
  WScript.Quit 1
End If

If Not fso.FileExists(runPs1) Then
  MsgBox "run.ps1 가 없습니다. ZIP을 모든 파일과 함께 풀었는지 확인하세요.", _
         vbCritical, "DOCX -> HWPX"
  WScript.Quit 1
End If

ans = MsgBox( _
  "이 폴더의 source.docx 를 final.hwpx 로 변환합니다." & vbCrLf & vbCrLf & _
  "약 30초~1분간 Word와 한컴 한글이 자동으로 잠깐씩 떴다 사라집니다." & vbCrLf & _
  "그 동안 마우스/키보드를 건드리지 말아 주세요." & vbCrLf & vbCrLf & _
  "지금 시작할까요?", _
  vbQuestion + vbYesNo + vbDefaultButton1, _
  "DOCX -> HWPX 변환")
If ans <> vbYes Then WScript.Quit 0

' Delete stale final.hwpx if any
If fso.FileExists(finalPath) Then fso.DeleteFile finalPath, True

' Run hidden, wait for completion
exitCode = shell.Run( _
  "powershell.exe -NoProfile -ExecutionPolicy Bypass -File """ & runPs1 & """", _
  0, True)

If exitCode = 0 And fso.FileExists(finalPath) Then
  ans = MsgBox( _
    "완료! final.hwpx 가 생성되었습니다." & vbCrLf & vbCrLf & _
    "지금 폴더를 열까요?", _
    vbInformation + vbYesNo, _
    "DOCX -> HWPX 변환")
  If ans = vbYes Then
    shell.Run "explorer.exe """ & scriptDir & """", 1, False
  End If
ElseIf fso.FileExists(finalPath) Then
  MsgBox "변환은 됐지만 일부 단계에서 경고가 있었습니다 (exit " & exitCode & ")." & vbCrLf & _
         "final.hwpx 는 정상 생성되었으니 한글로 열어보세요.", _
         vbExclamation, "DOCX -> HWPX 변환"
Else
  MsgBox _
    "변환에 실패했습니다 (exit code " & exitCode & ")." & vbCrLf & vbCrLf & _
    "체크리스트:" & vbCrLf & _
    " 1) Microsoft Word 설치 및 정상 실행 가능?" & vbCrLf & _
    " 2) 한컴 한글 2020 한 번 직접 실행해 라이선스 통과시켰는지?" & vbCrLf & _
    " 3) 한글 도구 > 환경설정 > 보안 > 스크립트 보안 = 보통/낮음?" & vbCrLf & vbCrLf & _
    "상세 로그를 보려면 같은 폴더의 run.cmd 를 더블클릭해 직접 실행해 보세요.", _
    vbCritical, "DOCX -> HWPX 변환"
End If
`;

// Fallback console runner (for troubleshooting)
const RUN_CMD = `@echo off
setlocal
cd /d "%~dp0"
echo === DOCX -> HWPX (console mode)
echo.
powershell -NoProfile -ExecutionPolicy Bypass -File ".\\run.ps1"
echo.
echo === Script finished. Press any key to close.
pause >nul
`;

const README_TXT = `DOCX -> HWPX Runner
====================

Generated by https://hwp-proposal-cloud.vercel.app

HOW TO USE (the easy way):

   *** Just double-click convert.vbs ***

   A dialog asks you to confirm. Word and Hancom Hangul briefly pop up
   and close. When done, you'll see a "Done!" dialog. Click yes and
   File Explorer opens with your final.hwpx ready.

REQUIREMENTS:

   - Microsoft Word
   - Hancom Hangul 2020 -- run it once interactively first to accept license

OPTIONAL (only if you turned on the compare report when building this ZIP):

   - ImageMagick    https://imagemagick.org/script/download.php#windows
   - Ghostscript    https://www.ghostscript.com/releases/gsdnld.html

TROUBLESHOOTING:

   If convert.vbs shows an error, run run.cmd instead -- it shows the
   raw output and stops at the first error so you can read it.

   Common errors:
     "Word.Application not found"   -> Microsoft Word not installed
     "Cannot create HwpCtrl"        -> Open Hancom Hangul once manually
     Hangul script security warning -> 한글 > 도구 > 환경설정 > 보안
                                      -> 스크립트 보안 -> 보통

ADVANCED:

   - run.cmd / run.ps1 are the same conversion in console form
   - Edit run.ps1 line "$Factor = " to tune the layout stretch (default 2.02)
   - All COM logic lives in pipeline/*.ps1 -- safe to read / modify
`;

function buildRunPs1({ factor, compare }) {
  const compareBlock = compare ? `
Write-Host "=== Step 4 (optional): compare rendered pages"
try {
  powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "compare_rendered_pages.ps1") \`
    -SourceDocx $source -CandidateHwpx $OutputFinal -WorkDir (Join-Path $Root "compare")
} catch {
  Write-Host "compare step failed (ImageMagick or Ghostscript missing). Skipping." -ForegroundColor Yellow
  Write-Host $_.Exception.Message -ForegroundColor Yellow
}
` : `
# compare step disabled at bundle time
`;

  return `param(
  [string]$SourceDocx  = ".\\source.docx",
  [string]$OutputFinal = ".\\final.hwpx",
  [string]$Factor      = "${factor}"
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
Set-Location $Root

$pipeline = Join-Path $Root "pipeline"
$source   = (Resolve-Path $SourceDocx).Path
$rich     = Join-Path $Root "word_rich_paste.hwpx"
$stretch  = Join-Path $Root "stretched.hwpx"

Write-Host "=== Step 1: Word DOCX -> Hangul HWPX (paste through Word + Hangul COM)"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "paste_word_to_new_hangul.ps1") \`
  -SourceDocx $source -OutputHwpx $rich

Write-Host "=== Step 2: stretch HWPX layout (factor $Factor)"
powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $pipeline "stretch_hwpx_layout.ps1") \`
  -InputHwpx $rich -OutputHwpx $stretch -Factor $Factor

Write-Host "=== Step 3: reflow through Hangul engine"
powershell -NoProfile -ExecutionPolicy Bypass -STA -File (Join-Path $pipeline "reflow_with_hangul_engine.ps1") \`
  -InputHwpx $stretch -OutputHwpx $OutputFinal
${compareBlock}
Write-Host ""
Write-Host "=== DONE: $OutputFinal" -ForegroundColor Green
`;
}

const $ = (id) => document.getElementById(id);

const els = {
  form: $("form"),
  docxInput: $("docxInput"),
  docxName: $("docxName"),
  factor: $("factor"),
  compare: $("compare"),
  run: $("run"),
  statusCard: $("statusCard"),
  status: $("jobStatus"),
  zipSize: $("zipSize"),
  log: $("jobLog"),
  downloads: $("downloads")
};

els.docxInput.addEventListener("change", () => {
  const f = els.docxInput.files?.[0];
  els.docxName.textContent = f ? `${f.name} (${(f.size / 1024).toFixed(1)} KB)` : "선택된 파일 없음";
});

els.form.addEventListener("submit", async (e) => {
  e.preventDefault();
  await build();
});

function log(line) {
  els.log.textContent += line + "\n";
  els.log.scrollTop = els.log.scrollHeight;
}

function setStatus(s) {
  els.status.textContent = s;
}

async function build() {
  const file = els.docxInput.files?.[0];
  if (!file) {
    alert("DOCX 파일을 선택해주세요.");
    return;
  }
  if (!/\.docx$/i.test(file.name)) {
    alert("DOCX 확장자 파일만 지원합니다.");
    return;
  }

  els.statusCard.classList.remove("hidden");
  els.log.textContent = "";
  els.downloads.innerHTML = "";
  els.zipSize.textContent = "-";
  els.run.disabled = true;

  try {
    setStatus("ZIP 만드는 중…");
    log(`▸ 입력 DOCX: ${file.name} (${(file.size / 1024).toFixed(1)} KB)`);

    const factor = (els.factor.value || "2.02").trim();
    const compareOn = els.compare.value === "yes";
    log(`▸ 설정: Factor=${factor}, 비교 리포트=${compareOn ? "켜짐" : "꺼짐"}`);

    const zip = new JSZip();
    // BOM so VBS file opens correctly with Korean characters in Windows
    zip.file("convert.vbs", "﻿" + CONVERT_VBS);
    zip.file("source.docx", file);
    zip.file("run.cmd", RUN_CMD);
    zip.file("run.ps1", buildRunPs1({ factor, compare: compareOn }));
    zip.file("README.txt", README_TXT);

    const pipelineFolder = zip.folder("pipeline");
    log(`▸ pipeline/*.ps1 ${PIPELINE_FILES.length}개 fetch`);
    for (const name of PIPELINE_FILES) {
      const resp = await fetch(`/pipeline/${name}`);
      if (!resp.ok) throw new Error(`pipeline/${name} 다운로드 실패: ${resp.status}`);
      const text = await resp.text();
      pipelineFolder.file(name, text);
    }

    log("▸ ZIP 압축 중…");
    const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
    const sizeKb = (blob.size / 1024).toFixed(1);
    els.zipSize.textContent = `${sizeKb} KB`;
    log(`▸ ZIP 생성 완료: ${sizeKb} KB`);

    const stamp = new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14);
    const zipName = `hwp-runner-${stamp}.zip`;
    appendDownload(els.downloads, zipName, blob, "변환 번들 ZIP 다운로드");

    setStatus("완료");
    log("▸ ZIP을 PC에서 풀고 convert.vbs 더블클릭하세요. 터미널 안 떠요.");
  } catch (error) {
    setStatus("실패");
    log("✕ " + (error.message || String(error)));
    console.error(error);
  } finally {
    els.run.disabled = false;
  }
}

function appendDownload(container, filename, blob, label) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.textContent = "↓ " + label;
  container.appendChild(a);
}
